server:
  port: 8081

spring:
  application:
   name: ms-usuario

  datasource:
    url: ${DB_URL:jdbc:oracle:thin:@y9yihlwya0utl6x4_medium?TNS_ADMIN=/Users/danielguzman/Desktop/Hospital_VM/Wallet_Y9YIHLWYA0UTL6X4}
    username: ${DB_USERNAME:ADMIN}
    password: ${DB_PASSWORD:FullStack-001}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 2
      minimum-idle: 1
  jpa:
    # Cambiado a 'database' en lugar de 'database-platform' para seguir el estándar moderno de Spring Boot 3
    database: oracle
    hibernate:
      ddl-auto: update
    show-sql: true
    # Evita el warning molesto en la consola sobre el contexto de la vista
    open-in-view: false

# Propiedades de Swagger
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html

# AGREGADO: Configuración para que se registre en tu servidor Eureka
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    # Esto ayuda a Eureka a identificar de forma única esta instancia en tu máquina
    instance-id: ${spring.application.name}:${server.port}